[package]
name = "messages"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Tugunchinov <tugunchinov.maxim@gmail.com>"]
description = "TODO"
build = "src/build.rs"

[dependencies]
prost = "0.12.3"
prost-build = "0.12.3"

[build-dependencies]
prost-build = "0.12.3"
